### ISSUE TITLE
Should galois keys be regenerated for each query?

### ISSUE THREAD

**Issue by Katherine-101** [ishtiyaque/FastPIR#2]
Hi! I have an issue about Galois keys in the code.

For the same client, is it necessary to regenerate the Galois keys before each query and send it to the server? Or only need to be generated once when the PIR service created? Is there a security problem if the keys are only generated once?

**Comment by ishtiyaque** [comment]
Generating Galois keys for a client is a one-time requirement when it first connects to the server and these keys can be reused for all subsequent PIR queries without any security issues. No need to regenerate Galois keys for every query. Thanks.
